### ISSUE TITLE
Text is missing in the pricing section

### ISSUE THREAD

**Issue by maqsudcoder** [jonasschmedtmann/html-css-course#1]
Text is missing in the pricing section. I found it from the live version of the new Omni food website. [Screenshot link](https://ibb.co/4NQrK9j)

**Comment by Abdallah-AJ** [comment]
Can you just leave at least the part of the code not all of it just the one of the text in order to try to help you?

**Comment by maqsudcoder** [comment]
Sorry, I thought it was a bug but now I have checked it from the course and it is not a bug.
